version: "3"

services:

  asterisk:
    image: andrius/asterisk
    volumes:
      - ./vol/asterisk/logs:/var/log/asterisk
      - ./vol/asterisk/config/extensions.conf:/etc/asterisk/extensions.conf
      - ./vol/asterisk/config/sip.conf:/etc/asterisk/sip.conf